package com.gopal.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK.
 */
public class Task {

    private Long id;
    /** Not-null value. */
    private String time;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String note;

    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    public Task(Long id, String time, String date, String note) {
        this.id = id;
        this.time = time;
        this.date = date;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getNote() {
        return note;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNote(String note) {
        this.note = note;
    }

}
